// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlxcyqegecillqbhtaww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpseGN5cWVnZWNpbGxxYmh0YXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1Nzg0NzIsImV4cCI6MjA1MTE1NDQ3Mn0.O1q2yjezQf8YlwHV6XtFJzJaBqo1W2KkjEoLR2SLSUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);